server:
    port: 8686
    compression:
        enabled: true
    connection-timeout: 3000
    tomcat:
        uri-encoding: utf-8

#debug: false

#logging:
#  file: /var/log/admin-manager.log

management:
  context-path: /management
  security:
    enabled: false

spring:
  jmx:
    default-domain: xxxblog
  application:
    name: xiexx-blog
  datasource:
    url: jdbc:mysql://localhost:3306/xiexx_blog?characterEncoding=utf-8
    username: root
    password: 123123
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
          max-active: 30
          initial-size: 5
          min-idle: 3
          max-wait: 60000
          time-between-eviction-runs-millis: 60000
          min-evictable-idle-time-millis: 300000
          test-while-idle: true
          test-on-borrow: false
          test-on-return: false
  cache:
    guava:
      #spec: maximumSize=500,expireAfterAccess=3600s
      spec: maximumSize=500

 #spring-boot-admin config
#  boot:
#      admin:
#        #这里是admin-manage的地址，/admin是admin-manage中配置的spring.spring.boot.admin.context-path
#        url: http://localhost:10000/admin
#        context-path: /admin

  thymeleaf:
      cache: false

      prefix: classpath:/public/themes/jiestyle/
      mode: LEGACYHTML5

#mybatis:
#    mapperLocations: classpath:mapping/*.xml
#    typeAliasesPackage: com.xxx.blog.domain.entity

blog:
  manage:
    ##允许访问博客管理api的机器
    allow: localhost,127.0.0.1,xiexx.tech

weixin:
  token: weiqiang
  aesKey:
  subscribe: '我是xiexx，极度热爱技术的资深IT男。我将持续分享Java的各项技术研究和职业经验，尽最大的努力解答你的各种疑问，一起进步，一起成长!
            任何相关的技术支持都可以尝试联系我，个人微信: xiexxcom ,或许可以帮到你。现在向公众号发送文本和语言消息，可以直接搜索xiexx博客文章哦，试试吧'

tulin:
  key:
  secret:

metaweblog:
  user: test
  pwd: test

sync:
  jianshu: true