#    dev 开发环境：开发环境是程序猿们专门用于开发的服务器，配置可以比较随意， 为了开发调试方便，一般打开全部错误报告。
#    qa 测试环境：一般是克隆一份生产环境的配置，一个程序在测试环境工作不正常，那么肯定不能把它发布到生产机上。
#    prod 生产环境：是值正式提供对外服务的，一般会关掉错误报告，打开错误日志。
spring:
  profiles:
    active: prod
